-- Buying list ordered quantity
ALTER TABLE buying_list
  ADD COLUMN IF NOT EXISTS ordered_quantity INTEGER NOT NULL DEFAULT 0;

UPDATE buying_list
SET ordered_quantity = requested_quantity
WHERE ordered_quantity = 0;

-- Arrivals table
CREATE TABLE IF NOT EXISTS arrivals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NULL,
  product_name TEXT NOT NULL,
  ordered_quantity INTEGER NOT NULL DEFAULT 0,
  received_quantity INTEGER NOT NULL DEFAULT 0,
  batch_name TEXT NOT NULL,
  confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Track if a batch has been sent to arrivals
ALTER TABLE order_batches
  ADD COLUMN IF NOT EXISTS arrivals_sent BOOLEAN NOT NULL DEFAULT FALSE;
